# Flight Data Analysis

dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [5]:
# dataset = pd.read_excel(r"D:\Downloads File\pandas practise file\EDA_PRACTISE_SET\flight_price.xlsx")

dataset = pd.read_excel(r"D:\Python Project\Flight_data_analysis\data\flight_price.xlsx")

In [125]:
df = dataset.copy()

In [126]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [127]:
df.shape

(10683, 11)

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [129]:
# drop null rows
df.dropna(inplace=True)

In [130]:
df.isna().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [131]:
df.duplicated().sum()

220

In [132]:
# Checking duplicated values
df[df.duplicated()]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
683,Jet Airways,1/06/2019,Delhi,Cochin,DEL → NAG → BOM → COK,14:35,04:25 02 Jun,13h 50m,2 stops,No info,13376
1061,Air India,21/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,22:00,19:15 22 May,21h 15m,2 stops,No info,10231
1348,Air India,18/05/2019,Delhi,Cochin,DEL → HYD → BOM → COK,17:15,19:15 19 May,26h,2 stops,No info,12392
1418,Jet Airways,6/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,05:30,04:25 07 Jun,22h 55m,2 stops,In-flight meal not included,10368
1674,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,18:25,21:20,2h 55m,non-stop,No info,7303
...,...,...,...,...,...,...,...,...,...,...,...
10594,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,12:35 28 Jun,13h 30m,2 stops,No info,12819
10616,Jet Airways,1/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,09:40,12:35 02 Jun,26h 55m,2 stops,No info,13014
10634,Jet Airways,6/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,09:40,12:35 07 Jun,26h 55m,2 stops,In-flight meal not included,11733
10672,Jet Airways,27/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,19:00 28 Jun,19h 55m,2 stops,In-flight meal not included,11150
10673,Jet Airways,27/05/2019,Delhi,Cochin,DEL → AMD → BOM → COK,13:25,04:25 28 May,15h,2 stops,No info,16704

In [133]:
df.duplicated(subset=df.columns.drop('Price')).sum()

419

No need to drop duplicate because price is variate

In [134]:
# Checking Unique Values
cat_col = df.select_dtypes(include='object').columns
for col in cat_col:
    print(f"{col} : {df[col].unique()}")

Airline : ['IndiGo' 'Air India' 'Jet Airways' 'SpiceJet' 'Multiple carriers' 'GoAir'
 'Vistara' 'Air Asia' 'Vistara Premium economy' 'Jet Airways Business'
 'Multiple carriers Premium economy' 'Trujet']
Date_of_Journey : ['24/03/2019' '1/05/2019' '9/06/2019' '12/05/2019' '01/03/2019'
 '24/06/2019' '12/03/2019' '27/05/2019' '1/06/2019' '18/04/2019'
 '9/05/2019' '24/04/2019' '3/03/2019' '15/04/2019' '12/06/2019'
 '6/03/2019' '21/03/2019' '3/04/2019' '6/05/2019' '15/05/2019'
 '18/06/2019' '15/06/2019' '6/04/2019' '18/05/2019' '27/06/2019'
 '21/05/2019' '06/03/2019' '3/06/2019' '15/03/2019' '3/05/2019'
 '9/03/2019' '6/06/2019' '24/05/2019' '09/03/2019' '1/04/2019'
 '21/04/2019' '21/06/2019' '27/03/2019' '18/03/2019' '12/04/2019'
 '9/04/2019' '1/03/2019' '03/03/2019' '27/04/2019']
Source : ['Banglore' 'Kolkata' 'Delhi' 'Chennai' 'Mumbai']
Destination : ['New Delhi' 'Banglore' 'Cochin' 'Kolkata' 'Delhi' 'Hyderabad']
Route : ['BLR → DEL' 'CCU → IXR → BBI → BLR' 'DEL → LKO → BOM → COK'
 'CCU → NAG → BLR' 'BLR → NAG → DEL' 'CCU → BLR' 'BLR → BOM → DEL'
 'DEL → BOM → COK' 'DEL → BLR → COK' 'MAA → CCU' 'CCU → BOM → BLR'
 'DEL → AMD → BOM → COK' 'DEL → PNQ → COK' 'DEL → CCU → BOM → COK'
 'BLR → COK → DEL' 'DEL → IDR → BOM → COK' 'DEL → LKO → COK'
 'CCU → GAU → DEL → BLR' 'DEL → NAG → BOM → COK' 'CCU → MAA → BLR'
 'DEL → HYD → COK' 'CCU → HYD → BLR' 'DEL → COK' 'CCU → DEL → BLR'
 'BLR → BOM → AMD → DEL' 'BOM → DEL → HYD' 'DEL → MAA → COK' 'BOM → HYD'
 'DEL → BHO → BOM → COK' 'DEL → JAI → BOM → COK' 'DEL → ATQ → BOM → COK'
 'DEL → JDH → BOM → COK' 'CCU → BBI → BOM → BLR' 'BLR → MAA → DEL'
 'DEL → GOI → BOM → COK' 'DEL → BDQ → BOM → COK' 'CCU → JAI → BOM → BLR'
 'CCU → BBI → BLR' 'BLR → HYD → DEL' 'DEL → TRV → COK'
 'CCU → IXR → DEL → BLR' 'DEL → IXU → BOM → COK' 'CCU → IXB → BLR'
 'BLR → BOM → JDH → DEL' 'DEL → UDR → BOM → COK' 'DEL → HYD → MAA → COK'
 'CCU → BOM → COK → BLR' 'BLR → CCU → DEL' 'CCU → BOM → GOI → BLR'
 'DEL → RPR → NAG → BOM → COK' 'DEL → HYD → BOM → COK'
 'CCU → DEL → AMD → BLR' 'CCU → PNQ → BLR' 'BLR → CCU → GAU → DEL'
 'CCU → DEL → COK → BLR' 'BLR → PNQ → DEL' 'BOM → JDH → DEL → HYD'
 'BLR → BOM → BHO → DEL' 'DEL → AMD → COK' 'BLR → LKO → DEL'
 'CCU → GAU → BLR' 'BOM → GOI → HYD' 'CCU → BOM → AMD → BLR'
 'CCU → BBI → IXR → DEL → BLR' 'DEL → DED → BOM → COK'
 'DEL → MAA → BOM → COK' 'BLR → AMD → DEL' 'BLR → VGA → DEL'
 'CCU → JAI → DEL → BLR' 'CCU → AMD → BLR' 'CCU → VNS → DEL → BLR'
 'BLR → BOM → IDR → DEL' 'BLR → BBI → DEL' 'BLR → GOI → DEL'
 'BOM → AMD → ISK → HYD' 'BOM → DED → DEL → HYD' 'DEL → IXC → BOM → COK'
 'CCU → PAT → BLR' 'BLR → CCU → BBI → DEL' 'CCU → BBI → HYD → BLR'
 'BLR → BOM → NAG → DEL' 'BLR → CCU → BBI → HYD → DEL' 'BLR → GAU → DEL'
 'BOM → BHO → DEL → HYD' 'BOM → JLR → HYD' 'BLR → HYD → VGA → DEL'
 'CCU → KNU → BLR' 'CCU → BOM → PNQ → BLR' 'DEL → BBI → COK'
 'BLR → VGA → HYD → DEL' 'BOM → JDH → JAI → DEL → HYD'
 'DEL → GWL → IDR → BOM → COK' 'CCU → RPR → HYD → BLR' 'CCU → VTZ → BLR'
 'CCU → DEL → VGA → BLR' 'BLR → BOM → IDR → GWL → DEL'
 'CCU → DEL → COK → TRV → BLR' 'BOM → COK → MAA → HYD' 'BOM → NDC → HYD'
 'BLR → BDQ → DEL' 'CCU → BOM → TRV → BLR' 'CCU → BOM → HBX → BLR'
 'BOM → BDQ → DEL → HYD' 'BOM → CCU → HYD' 'BLR → TRV → COK → DEL'
 'BLR → IDR → DEL' 'CCU → IXZ → MAA → BLR' 'CCU → GAU → IMF → DEL → BLR'
 'BOM → GOI → PNQ → HYD' 'BOM → BLR → CCU → BBI → HYD' 'BOM → MAA → HYD'
 'BLR → BOM → UDR → DEL' 'BOM → UDR → DEL → HYD' 'BLR → VGA → VTZ → DEL'
 'BLR → HBX → BOM → BHO → DEL' 'CCU → IXA → BLR' 'BOM → RPR → VTZ → HYD'
 'BLR → HBX → BOM → AMD → DEL' 'BOM → IDR → DEL → HYD' 'BOM → BLR → HYD'
 'BLR → STV → DEL' 'CCU → IXB → DEL → BLR' 'BOM → JAI → DEL → HYD'
 'BOM → VNS → DEL → HYD' 'BLR → HBX → BOM → NAG → DEL'
 'BLR → BOM → IXC → DEL' 'BLR → CCU → BBI → HYD → VGA → DEL'
 'BOM → BBI → HYD']
Dep_Time : ['22:20' '05:50' '09:25' '18:05' '16:50' '09:00' '18:55' '08:00' '08:55'
 '11:25' '09:45' '20:20' '11:40' '21:10' '17:15' '16:40' '08:45' '14:00'
 '20:15' '16:00' '14:10' '22:00' '04:00' '21:25' '21:50' '07:00' '07:05'
 '09:50' '14:35' '10:35' '15:05' '14:15' '06:45' '20:55' '11:10' '05:45'
 '19:00' '23:05' '11:00' '09:35' '21:15' '23:55' '19:45' '08:50' '15:40'
 '06:05' '15:00' '13:55' '05:55' '13:20' '05:05' '06:25' '17:30' '08:20'
 '19:55' '06:30' '14:05' '02:00' '09:40' '08:25' '20:25' '13:15' '02:15'
 '16:55' '20:45' '05:15' '19:50' '20:00' '06:10' '19:30' '04:45' '12:55'
 '18:15' '17:20' '15:25' '23:00' '12:00' '14:45' '11:50' '11:30' '14:40'
 '19:10' '06:00' '23:30' '07:35' '13:05' '12:30' '15:10' '12:50' '18:25'
 '16:30' '00:40' '06:50' '13:00' '19:15' '01:30' '17:00' '10:00' '19:35'
 '15:30' '12:10' '16:10' '20:35' '22:25' '21:05' '05:35' '05:10' '06:40'
 '15:15' '00:30' '08:30' '07:10' '05:30' '14:25' '05:25' '10:20' '17:45'
 '13:10' '22:10' '04:55' '17:50' '21:20' '06:20' '15:55' '20:30' '17:25'
 '09:30' '07:30' '02:35' '10:55' '17:10' '09:10' '18:45' '15:20' '22:50'
 '14:55' '14:20' '13:25' '22:15' '11:05' '16:15' '20:10' '06:55' '19:05'
 '07:55' '07:45' '10:10' '08:15' '11:35' '21:00' '17:55' '16:45' '18:20'
 '03:50' '08:35' '19:20' '20:05' '17:40' '04:40' '17:35' '09:55' '05:00'
 '18:00' '02:55' '20:40' '22:55' '22:40' '21:30' '08:10' '17:05' '07:25'
 '15:45' '09:15' '15:50' '11:45' '22:05' '18:35' '00:25' '19:40' '20:50'
 '22:45' '10:30' '23:25' '11:55' '10:45' '11:15' '12:20' '14:30' '07:15'
 '01:35' '18:40' '09:20' '21:55' '13:50' '01:40' '00:20' '04:15' '13:45'
 '18:30' '06:15' '02:05' '12:15' '13:30' '06:35' '10:05' '08:40' '03:05'
 '21:35' '16:35' '02:30' '16:25' '05:40' '15:35' '13:40' '07:20' '04:50'
 '12:45' '10:25' '12:05' '11:20' '21:40' '03:00']
Arrival_Time : ['01:10 22 Mar' '13:15' '04:25 10 Jun' ... '06:50 10 Mar' '00:05 19 Mar'
 '21:20 13 Mar']
Duration : ['2h 50m' '7h 25m' '19h' '5h 25m' '4h 45m' '2h 25m' '15h 30m' '21h 5m'
 '25h 30m' '7h 50m' '13h 15m' '2h 35m' '2h 15m' '12h 10m' '26h 35m'
 '4h 30m' '22h 35m' '23h' '20h 35m' '5h 10m' '15h 20m' '2h 55m' '13h 20m'
 '15h 10m' '5h 45m' '5h 55m' '13h 25m' '22h' '5h 30m' '10h 25m' '5h 15m'
 '2h 30m' '6h 15m' '11h 55m' '11h 5m' '8h 30m' '22h 5m' '2h 45m' '12h'
 '16h 5m' '19h 55m' '3h 15m' '25h 20m' '3h' '16h 15m' '15h 5m' '6h 30m'
 '25h 5m' '12h 25m' '27h 20m' '10h 15m' '10h 30m' '1h 30m' '1h 25m'
 '26h 30m' '7h 20m' '13h 30m' '5h' '19h 5m' '14h 50m' '2h 40m' '22h 10m'
 '9h 35m' '10h' '21h 20m' '18h 45m' '12h 20m' '18h' '9h 15m' '17h 30m'
 '16h 35m' '12h 15m' '7h 30m' '24h' '8h 55m' '7h 10m' '14h 30m' '30h 20m'
 '15h' '12h 45m' '10h 10m' '15h 25m' '14h 5m' '20h 15m' '23h 10m'
 '18h 10m' '16h' '2h 20m' '8h' '16h 55m' '3h 10m' '14h' '23h 50m'
 '21h 40m' '21h 15m' '10h 50m' '8h 15m' '8h 35m' '11h 50m' '27h 35m'
 '8h 25m' '20h 55m' '4h 50m' '8h 10m' '24h 25m' '23h 35m' '25h 45m'
 '26h 10m' '28h 50m' '25h 15m' '9h 20m' '9h 10m' '3h 5m' '11h 30m'
 '9h 30m' '17h 35m' '5h 5m' '25h 50m' '20h' '13h' '18h 25m' '24h 10m'
 '4h 55m' '25h 35m' '6h 20m' '18h 40m' '19h 25m' '29h 20m' '9h 5m'
 '10h 45m' '11h 40m' '22h 55m' '37h 25m' '25h 40m' '13h 55m' '8h 40m'
 '23h 30m' '12h 35m' '24h 15m' '1h 20m' '11h' '11h 15m' '14h 35m'
 '12h 55m' '9h' '7h 40m' '11h 45m' '24h 55m' '17h 5m' '29h 55m' '22h 15m'
 '14h 40m' '7h 15m' '20h 10m' '20h 45m' '27h' '24h 30m' '20h 25m' '5h 35m'
 '14h 45m' '5h 40m' '4h 5m' '15h 55m' '7h 45m' '28h 20m' '4h 20m' '3h 40m'
 '8h 50m' '23h 45m' '24h 45m' '21h 35m' '8h 5m' '6h 25m' '15h 50m'
 '26h 25m' '24h 50m' '26h' '23h 5m' '7h 55m' '26h 20m' '23h 15m' '5h 20m'
 '4h' '9h 45m' '8h 20m' '17h 25m' '7h 5m' '34h 5m' '6h 5m' '5h 50m' '7h'
 '4h 25m' '13h 45m' '19h 15m' '22h 30m' '16h 25m' '13h 50m' '27h 5m'
 '28h 10m' '4h 40m' '15h 40m' '4h 35m' '18h 30m' '38h 15m' '6h 35m'
 '12h 30m' '11h 20m' '7h 35m' '29h 35m' '26h 55m' '23h 40m' '12h 50m'
 '9h 50m' '21h 55m' '10h 55m' '21h 10m' '20h 40m' '30h' '13h 10m' '8h 45m'
 '6h 10m' '17h 45m' '21h 45m' '3h 55m' '17h 20m' '30h 30m' '21h 25m'
 '12h 40m' '24h 35m' '19h 10m' '22h 40m' '14h 55m' '21h' '6h 45m'
 '28h 40m' '9h 40m' '16h 40m' '16h 20m' '16h 45m' '1h 15m' '6h 55m'
 '11h 25m' '14h 20m' '12h 5m' '24h 5m' '28h 15m' '17h 50m' '20h 20m'
 '28h 5m' '10h 20m' '14h 15m' '35h 15m' '35h 35m' '26h 40m' '28h'
 '14h 25m' '13h 5m' '37h 20m' '36h 10m' '25h 55m' '35h 5m' '19h 45m'
 '27h 55m' '47h' '10h 35m' '1h 35m' '16h 10m' '38h 20m' '6h' '16h 50m'
 '14h 10m' '23h 20m' '17h 40m' '11h 35m' '18h 20m' '6h 40m' '30h 55m'
 '24h 40m' '29h 50m' '28h 25m' '17h 15m' '22h 45m' '25h 25m' '21h 50m'
 '33h 15m' '30h 15m' '3h 35m' '27h 40m' '30h 25m' '18h 50m' '27h 45m'
 '15h 15m' '10h 40m' '26h 15m' '36h 25m' '26h 50m' '15h 45m' '19h 40m'
 '22h 25m' '19h 35m' '25h' '26h 45m' '38h' '4h 15m' '25h 10m' '18h 15m'
 '6h 50m' '23h 55m' '17h 55m' '23h 25m' '17h 10m' '24h 20m' '28h 30m'
 '27h 10m' '19h 20m' '15h 35m' '9h 25m' '21h 30m' '34h 25m' '18h 35m'
 '29h 40m' '26h 5m' '29h 5m' '27h 25m' '16h 30m' '11h 10m' '28h 55m'
 '29h 10m' '34h' '30h 40m' '30h 45m' '32h 55m' '10h 5m' '35h 20m' '32h 5m'
 '31h 40m' '19h 50m' '33h 45m' '30h 10m' '13h 40m' '19h 30m' '31h 30m'
 '34h 30m' '27h 50m' '38h 35m' '42h 5m' '4h 10m' '39h 5m' '3h 50m' '5m'
 '32h 30m' '31h 55m' '33h 20m' '27h 30m' '18h 55m' '9h 55m' '41h 20m'
 '20h 5m' '31h 50m' '42h 45m' '3h 25m' '37h 10m' '29h 30m' '32h 20m'
 '20h 50m' '40h 20m' '13h 35m' '47h 40m']
Total_Stops : ['non-stop' '2 stops' '1 stop' '3 stops' '4 stops']
Additional_Info : ['No info' 'In-flight meal not included' 'No check-in baggage included'
 '1 Short layover' 'No Info' '1 Long layover' 'Change airports'
 'Business class' 'Red-eye flight' '2 Long layover']

**Date of Journey Editing**

In [135]:
df['Date_of_Journey'] = pd.to_datetime(df['Date_of_Journey'], format='%d/%m/%Y')

In [136]:
df['Date_of_Journey']

0       2019-03-24
1       2019-05-01
2       2019-06-09
3       2019-05-12
4       2019-03-01
           ...
10678   2019-04-09
10679   2019-04-27
10680   2019-04-27
10681   2019-03-01
10682   2019-05-09
Name: Date_of_Journey, Length: 10682, dtype: datetime64[ns]

In [137]:
# For ML
df['Journey_day'] = df['Date_of_Journey'].dt.day
df['Journey_month'] = df['Date_of_Journey'].dt.month
df['Journey_weekday'] = df['Date_of_Journey'].dt.weekday

# Drop the date of journey column as we have extracted day, month and weekday
# df.drop('Date_of_Journey', axis=1, inplace=True)

In [138]:
df['Journey_day'].unique()

array([24,  1,  9, 12, 27, 18,  3, 15,  6, 21])

**Depterature Time Editing**

In [139]:
# df['Dep_Time'] = pd.to_datetime(df['Dep_Time'], format='%H:%M').dt.time  # I give only time output

In [140]:
# df['Dep_min'].unique()

In [141]:
# For ML
df['Dep_Time'] = pd.to_datetime(df['Dep_Time'])   # It give date and time output

df['Dep_hour'] = df['Dep_Time'].dt.hour
df['Dep_min'] = df['Dep_Time'].dt.minute

# Drop the departure time column as we have extracted hour and minute
# df.drop('Dep_Time', axis=1, inplace=True)

In [142]:
df['Dep_hour']

0        22
1         5
2         9
3        18
4        16
         ..
10678    19
10679    20
10680     8
10681    11
10682    10
Name: Dep_hour, Length: 10682, dtype: int32

**Arrival Time Editing**

In [143]:
df['Arrival_Time'].unique()

array(['01:10 22 Mar', '13:15', '04:25 10 Jun', ..., '06:50 10 Mar',
       '00:05 19 Mar', '21:20 13 Mar'], dtype=object)

In [144]:
df[['Arr_Time', 'Arr_Date']] = df['Arrival_Time'].str.split(' ', n=1, expand=True)

In [145]:
df['Arrival_hour'] = pd.to_datetime(df['Arr_Time']).dt.hour
df['Arrival_min'] = pd.to_datetime(df['Arr_Time']).dt.minute

In [146]:
# Jaha Arr_Date available hai → use karo
df['Arr_Date'] = df['Arr_Date'].fillna('')

# Combine karne ke liye year add karna padega
df['Arrival_Date'] = df.apply(
    lambda row: 
    pd.to_datetime(row['Arr_Date'] + ' 2019', format='%d %b %Y')
    if row['Arr_Date'] != '' 
    else row['Date_of_Journey'],
    axis=1
)

In [147]:
df['Arrival_Date'].unique()

<DatetimeArray>
['2019-03-22 00:00:00', '2019-05-01 00:00:00', '2019-06-10 00:00:00',
 '2019-05-12 00:00:00', '2019-03-01 00:00:00', '2019-06-24 00:00:00',
 '2019-03-13 00:00:00', '2019-03-02 00:00:00', '2019-05-27 00:00:00',
 '2019-06-01 00:00:00', '2019-04-18 00:00:00', '2019-05-10 00:00:00',
 '2019-04-24 00:00:00', '2019-03-04 00:00:00', '2019-04-15 00:00:00',
 '2019-06-13 00:00:00', '2019-05-28 00:00:00', '2019-03-06 00:00:00',
 '2019-03-19 00:00:00', '2019-04-03 00:00:00', '2019-05-07 00:00:00',
 '2019-06-02 00:00:00', '2019-05-15 00:00:00', '2019-06-18 00:00:00',
 '2019-06-15 00:00:00', '2019-04-06 00:00:00', '2019-06-16 00:00:00',
 '2019-05-18 00:00:00', '2019-06-27 00:00:00', '2019-05-21 00:00:00',
 '2019-06-03 00:00:00', '2019-03-15 00:00:00', '2019-05-19 00:00:00',
 '2019-05-06 00:00:00', '2019-03-21 00:00:00', '2019-03-24 00:00:00',
 '2019-05-03 00:00:00', '2019-05-16 00:00:00', '2019-06-28 00:00:00',
 '2019-03-09 00:00:00', '2019-05-02 00:00:00', '2019-03-28 00:00:00',
 '2019-06-19 00:00:00', '2019-04-04 00:00:00', '2019-03-25 00:00:00',
 '2019-03-07 00:00:00', '2019-06-06 00:00:00', '2019-05-24 00:00:00',
 '2019-03-12 00:00:00', '2019-06-25 00:00:00', '2019-06-07 00:00:00',
 '2019-04-01 00:00:00', '2019-05-25 00:00:00', '2019-04-21 00:00:00',
 '2019-06-21 00:00:00', '2019-05-13 00:00:00', '2019-03-27 00:00:00',
 '2019-03-16 00:00:00', '2019-04-12 00:00:00', '2019-06-12 00:00:00',
 '2019-05-09 00:00:00', '2019-04-09 00:00:00', '2019-05-22 00:00:00',
 '2019-03-03 00:00:00', '2019-04-10 00:00:00', '2019-06-09 00:00:00',
 '2019-06-04 00:00:00', '2019-03-18 00:00:00', '2019-05-20 00:00:00',
 '2019-04-28 00:00:00', '2019-04-25 00:00:00', '2019-03-10 00:00:00',
 '2019-04-27 00:00:00', '2019-04-19 00:00:00', '2019-04-13 00:00:00',
 '2019-04-02 00:00:00', '2019-03-23 00:00:00', '2019-04-22 00:00:00',
 '2019-05-11 00:00:00', '2019-04-07 00:00:00', '2019-03-08 00:00:00',
 '2019-03-05 00:00:00', '2019-06-22 00:00:00', '2019-05-04 00:00:00',
 '2019-05-26 00:00:00', '2019-04-16 00:00:00', '2019-06-26 00:00:00',
 '2019-05-29 00:00:00', '2019-06-29 00:00:00', '2019-03-29 00:00:00',
 '2019-05-23 00:00:00', '2019-06-17 00:00:00']
Length: 92, dtype: datetime64[ns]

In [148]:
df['Arrival_Day'] = df['Arrival_Date'].dt.day

In [149]:
df['Journey_Diff_Days'] = (df['Arrival_Date'] - df['Date_of_Journey']).dt.days

**Duration Editing**

In [150]:
df['Duration'].unique()

array(['2h 50m', '7h 25m', '19h', '5h 25m', '4h 45m', '2h 25m', '15h 30m',
       '21h 5m', '25h 30m', '7h 50m', '13h 15m', '2h 35m', '2h 15m',
       '12h 10m', '26h 35m', '4h 30m', '22h 35m', '23h', '20h 35m',
       '5h 10m', '15h 20m', '2h 55m', '13h 20m', '15h 10m', '5h 45m',
       '5h 55m', '13h 25m', '22h', '5h 30m', '10h 25m', '5h 15m',
       '2h 30m', '6h 15m', '11h 55m', '11h 5m', '8h 30m', '22h 5m',
       '2h 45m', '12h', '16h 5m', '19h 55m', '3h 15m', '25h 20m', '3h',
       '16h 15m', '15h 5m', '6h 30m', '25h 5m', '12h 25m', '27h 20m',
       '10h 15m', '10h 30m', '1h 30m', '1h 25m', '26h 30m', '7h 20m',
       '13h 30m', '5h', '19h 5m', '14h 50m', '2h 40m', '22h 10m',
       '9h 35m', '10h', '21h 20m', '18h 45m', '12h 20m', '18h', '9h 15m',
       '17h 30m', '16h 35m', '12h 15m', '7h 30m', '24h', '8h 55m',
       '7h 10m', '14h 30m', '30h 20m', '15h', '12h 45m', '10h 10m',
       '15h 25m', '14h 5m', '20h 15m', '23h 10m', '18h 10m', '16h',
       '2h 20m', '8h', '16h 55m', '3h 10m', '14h', '23h 50m', '21h 40m',
       '21h 15m', '10h 50m', '8h 15m', '8h 35m', '11h 50m', '27h 35m',
       '8h 25m', '20h 55m', '4h 50m', '8h 10m', '24h 25m', '23h 35m',
       '25h 45m', '26h 10m', '28h 50m', '25h 15m', '9h 20m', '9h 10m',
       '3h 5m', '11h 30m', '9h 30m', '17h 35m', '5h 5m', '25h 50m', '20h',
       '13h', '18h 25m', '24h 10m', '4h 55m', '25h 35m', '6h 20m',
       '18h 40m', '19h 25m', '29h 20m', '9h 5m', '10h 45m', '11h 40m',
       '22h 55m', '37h 25m', '25h 40m', '13h 55m', '8h 40m', '23h 30m',
       '12h 35m', '24h 15m', '1h 20m', '11h', '11h 15m', '14h 35m',
       '12h 55m', '9h', '7h 40m', '11h 45m', '24h 55m', '17h 5m',
       '29h 55m', '22h 15m', '14h 40m', '7h 15m', '20h 10m', '20h 45m',
       '27h', '24h 30m', '20h 25m', '5h 35m', '14h 45m', '5h 40m',
       '4h 5m', '15h 55m', '7h 45m', '28h 20m', '4h 20m', '3h 40m',
       '8h 50m', '23h 45m', '24h 45m', '21h 35m', '8h 5m', '6h 25m',
       '15h 50m', '26h 25m', '24h 50m', '26h', '23h 5m', '7h 55m',
       '26h 20m', '23h 15m', '5h 20m', '4h', '9h 45m', '8h 20m',
       '17h 25m', '7h 5m', '34h 5m', '6h 5m', '5h 50m', '7h', '4h 25m',
       '13h 45m', '19h 15m', '22h 30m', '16h 25m', '13h 50m', '27h 5m',
       '28h 10m', '4h 40m', '15h 40m', '4h 35m', '18h 30m', '38h 15m',
       '6h 35m', '12h 30m', '11h 20m', '7h 35m', '29h 35m', '26h 55m',
       '23h 40m', '12h 50m', '9h 50m', '21h 55m', '10h 55m', '21h 10m',
       '20h 40m', '30h', '13h 10m', '8h 45m', '6h 10m', '17h 45m',
       '21h 45m', '3h 55m', '17h 20m', '30h 30m', '21h 25m', '12h 40m',
       '24h 35m', '19h 10m', '22h 40m', '14h 55m', '21h', '6h 45m',
       '28h 40m', '9h 40m', '16h 40m', '16h 20m', '16h 45m', '1h 15m',
       '6h 55m', '11h 25m', '14h 20m', '12h 5m', '24h 5m', '28h 15m',
       '17h 50m', '20h 20m', '28h 5m', '10h 20m', '14h 15m', '35h 15m',
       '35h 35m', '26h 40m', '28h', '14h 25m', '13h 5m', '37h 20m',
       '36h 10m', '25h 55m', '35h 5m', '19h 45m', '27h 55m', '47h',
       '10h 35m', '1h 35m', '16h 10m', '38h 20m', '6h', '16h 50m',
       '14h 10m', '23h 20m', '17h 40m', '11h 35m', '18h 20m', '6h 40m',
       '30h 55m', '24h 40m', '29h 50m', '28h 25m', '17h 15m', '22h 45m',
       '25h 25m', '21h 50m', '33h 15m', '30h 15m', '3h 35m', '27h 40m',
       '30h 25m', '18h 50m', '27h 45m', '15h 15m', '10h 40m', '26h 15m',
       '36h 25m', '26h 50m', '15h 45m', '19h 40m', '22h 25m', '19h 35m',
       '25h', '26h 45m', '38h', '4h 15m', '25h 10m', '18h 15m', '6h 50m',
       '23h 55m', '17h 55m', '23h 25m', '17h 10m', '24h 20m', '28h 30m',
       '27h 10m', '19h 20m', '15h 35m', '9h 25m', '21h 30m', '34h 25m',
       '18h 35m', '29h 40m', '26h 5m', '29h 5m', '27h 25m', '16h 30m',
       '11h 10m', '28h 55m', '29h 10m', '34h', '30h 40m', '30h 45m',
       '32h 55m', '10h 5m', '35h 20m', '32h 5m', '31h 40m', '19h 50m',
       '33h 45m', '30h 10m', '13h 40m', '19h 30m', '31h 30m', '34h 30m',
       '27h 50m', '38h 35m', '42h 5m', '4h 10m', '39h 5m', '3h 50m', '5m',
       '32h 30m', '31h 55m', '33h 20m', '27h 30m', '18h 55m', '9h 55m',
       '41h 20m', '20h 5m', '31h 50m', '42h 45m', '3h 25m', '37h 10m',
       '29h 30m', '32h 20m', '20h 50m', '40h 20m', '13h 35m', '47h 40m'],
      dtype=object)

In [151]:
df['Duration'].isna().sum()

0

In [152]:
df['Duration'].str.extract('(\d+)m').isna().sum()

0    1031
dtype: int64

In [153]:
df['Duration_hours'] = df['Duration'].str.extract('(\d+)h').fillna(0).astype(int)
df['Duration_minutes'] = df['Duration'].str.extract('(\d+)m').fillna(0).astype(int)

In [154]:
# Missing minutes filling
df['Duration'] = df['Duration'].apply(
    lambda x: x if 'm' in x else x + ' 0m'
)

In [155]:
# yeha nan value fill with zero and extract hour and minute
df['Duration_hours'] = df['Duration'].str.extract('(\d+)h').astype(float)
df['Duration_minutes'] = df['Duration'].str.extract('(\d+)m').astype(int)

In [156]:
df['Duration_hours']
df['Duration_minutes']

0        50
1        25
2         0
3        25
4        45
         ..
10678    30
10679    35
10680     0
10681    40
10682    20
Name: Duration_minutes, Length: 10682, dtype: int32

In [157]:
# Calculating total duration in minutes
df['Duration_total_mins'] = df['Duration_hours']*60 + df['Duration_minutes']

In [158]:
df['Duration_total_mins']

0         170.0
1         445.0
2        1140.0
3         325.0
4         285.0
          ...
10678     150.0
10679     155.0
10680     180.0
10681     160.0
10682     500.0
Name: Duration_total_mins, Length: 10682, dtype: float64

**Total Stops Editing**

In [159]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [160]:
df['Total_Stops'] = df['Total_Stops'].map({
    'non-stop': 0,
    '1 stop': 1,
    '2 stops': 2,
    '3 stops': 3,
    '4 stops': 4
})

In [161]:
df['Total_Stops'].isna().sum()

0

In [162]:
df['Total_Stops'].unique()

array([0, 2, 1, 3, 4], dtype=int64)

**Additional Info Editing**

In [163]:
df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [164]:
df['Additional_Info'].isna().sum()

0

In [165]:
df['Additional_Info'] = df['Additional_Info'].str.lower()

In [166]:
df['Additional_Info'].value_counts()

Additional_Info
no info                         8347
in-flight meal not included     1982
no check-in baggage included     320
1 long layover                    19
change airports                    7
business class                     4
1 short layover                    1
red-eye flight                     1
2 long layover                     1
Name: count, dtype: int64

In [167]:
# For ML
df['Additional_Info'] = df['Additional_Info'].str.lower()

df['Additional_Info_flag'] = df['Additional_Info'].apply(
    lambda x: 0 if x == 'no info' else 1
)

In [168]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'Journey_day', 'Journey_month',
       'Journey_weekday', 'Dep_hour', 'Dep_min', 'Arr_Time', 'Arr_Date',
       'Arrival_hour', 'Arrival_min', 'Arrival_Date', 'Arrival_Day',
       'Journey_Diff_Days', 'Duration_hours', 'Duration_minutes',
       'Duration_total_mins', 'Additional_Info_flag'],
      dtype='object')

##### Drop the date columns

In [169]:
df.drop(columns=['Date_of_Journey', 'Dep_Time', 'Arrival_Time', 'Arr_Time', 'Arr_Date', 'Duration', 'Additional_Info'], inplace=True)

In [170]:
df.drop('Arrival_Date', axis=1, inplace=True)

In [171]:
df.drop('Route',axis=1, inplace=True)

In [172]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Airline               10682 non-null  object
 1   Source                10682 non-null  object
 2   Destination           10682 non-null  object
 3   Total_Stops           10682 non-null  int64
 4   Price                 10682 non-null  int64
 5   Journey_day           10682 non-null  int32
 6   Journey_month         10682 non-null  int32
 7   Journey_weekday       10682 non-null  int32
 8   Dep_hour              10682 non-null  int32
 9   Dep_min               10682 non-null  int32
 10  Arrival_hour          10682 non-null  int32
 11  Arrival_min           10682 non-null  int32
 12  Arrival_Day           10682 non-null  int32
 13  Journey_Diff_Days     10682 non-null  int64
 14  Duration_hours        10681 non-null  float64
 15  Duration_minutes      10682 non-null  int32
 16  Duration_total_mins   10681 non-null  float64
 17  Additional_Info_flag  10682 non-null  int64
dtypes: float64(2), int32(9), int64(4), object(3)
memory usage: 1.2+ MB

In [173]:
df.fillna(0, inplace=True)

In [174]:
# Save cleaned data
# df.to_csv('cleaned_flight_data.csv', index=False)

In [175]:
df.describe()

,Total_Stops,Price,Journey_day,Journey_month,Journey_weekday,Dep_hour,Dep_min,Arrival_hour,Arrival_min,Arrival_Day,Journey_Diff_Days,Duration_hours,Duration_minutes,Duration_total_mins,Additional_Info_flag
count,10682.000000,10682.000000,10682.000000,10682.000000,10682.000000,10682.000000,10682.000000,10682.000000,10682.000000,10682.000000,10682.000000,10682.000000,10682.000000,10682.000000,10682.000000
mean,0.824190,9087.214567,13.509081,4.708575,2.935125,12.491013,24.409287,13.349186,24.690601,13.908163,0.399083,10.244898,28.326624,643.020034,0.218592
std,0.675229,4611.548810,8.479363,1.164408,2.006591,5.748820,18.767801,6.859317,16.506808,8.466862,0.605325,8.494916,16.945817,507.830724,0.413310
min,0.000000,1759.000000,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,-5.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,5277.000000,6.000000,3.000000,1.000000,8.000000,5.000000,8.000000,10.000000,7.000000,0.000000,2.000000,15.000000,170.000000,0.000000
50%,1.000000,8372.000000,12.000000,5.000000,3.000000,11.000000,25.000000,14.000000,25.000000,13.000000,0.000000,8.000000,30.000000,520.000000,0.000000
75%,1.000000,12373.000000,21.000000,6.000000,5.000000,18.000000,40.000000,19.000000,35.000000,21.000000,1.000000,15.000000,45.000000,930.000000,0.000000
max,4.000000,79512.000000,27.000000,6.000000,6.000000,23.000000,55.000000,23.000000,55.000000,29.000000,4.000000,47.000000,55.000000,2860.000000,1.000000

### Without Pipeline

##### **Train Test Split**

In [176]:
from sklearn.model_selection import train_test_split
x = df.drop('Price', axis=1)
y = df['Price']

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [177]:
# OneHotEncoding for categorical variables
cat_col = x_train.select_dtypes(include='object').columns
x_train = pd.get_dummies(x_train, columns=cat_col, drop_first=True)
x_test = pd.get_dummies(x_test, columns=cat_col, drop_first=True)

# Ensure x_train and x_test have the same columns
x_train, x_test = x_train.align(x_test, join='left', axis=1, fill_value=0)

In [178]:
x_train.shape, x_test.shape

((8545, 34), (2137, 34))

##### RandomForestRegressor

In [216]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

rf_model = RandomForestRegressor(n_estimators=160, max_depth=20, random_state=42)
rf_model.fit(x_train,y_train)

RandomForestRegressor(max_depth=20, n_estimators=160, random_state=42)

In [217]:
# Make predictions
rf_pred = rf_model.predict(x_test)

# Evaluate the model
mae = mean_absolute_error(y_test, rf_pred)
mse = mean_squared_error(y_test, rf_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, rf_pred)

print(f"Mean Absolute Error: {mae}")
print(f"Mean Squared Error: {mse}")
print(f"Root Mean Squared Error: {rmse}")
print(f"R² Score: {r2}")

Mean Absolute Error: 623.6477460371635
Mean Squared Error: 2083919.0642273894
Root Mean Squared Error: 1443.5785618480863
R² Score: 0.9033524895354154

##### XGBOOST

In [218]:
from xgboost import XGBRegressor

# build and train XGBoost
xgb = XGBRegressor(
    n_estimators=200,
    max_depth=8,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
    tree_method="hist"  # fast on moderate datasets
)
xgb.fit(x_train, y_train)

# 6) predict, evaluate
xgb_pred = xgb.predict(x_test)
mae = mean_absolute_error(y_test, xgb_pred)
mse = mean_squared_error(y_test, xgb_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, xgb_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2:", r2)

MAE: 677.7969360351562
MSE: 1864602.125
RMSE: 1365.5043482171707
R2: 0.9135239124298096

##### LightGBM

In [ ]:
# pip install lightgbm

Collecting lightgbm
Note: you may need to restart the kernel to use updated packages.  Using cached lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)

Requirement already satisfied: numpy>=1.17.0 in C:\Users\subas\AppData\Roaming\Python\Python312\site-packages (from lightgbm) (1.26.4)
Requirement already satisfied: scipy in C:\Users\subas\AppData\Roaming\Python\Python312\site-packages (from lightgbm) (1.17.1)
Using cached lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0

In [225]:
from lightgbm import LGBMRegressor

lgb_model =LGBMRegressor(
        n_estimators=200,
        learning_rate=0.1,
        max_depth=12,
        random_state=42)

lgb_model.fit(x_train, y_train)

lgb_pred = lgb_model.predict(x_test)
mae = mean_absolute_error(y_test, lgb_pred)
mse = mean_squared_error(y_test, lgb_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, lgb_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2:", r2)

MAE: 810.8915145164303
MSE: 2204812.8628940973
RMSE: 1484.8612268135016
R2: 0.8977457052450303

##### Pipeline Process

In [265]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.impute import SimpleImputer
# from sklearn.ensemble import RandomForestRegressor
# from xgboost import XGBRegressor

In [266]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Airline               10682 non-null  object
 1   Source                10682 non-null  object
 2   Destination           10682 non-null  object
 3   Total_Stops           10682 non-null  int64
 4   Journey_day           10682 non-null  int32
 5   Journey_month         10682 non-null  int32
 6   Journey_weekday       10682 non-null  int32
 7   Dep_hour              10682 non-null  int32
 8   Dep_min               10682 non-null  int32
 9   Arrival_hour          10682 non-null  int32
 10  Arrival_min           10682 non-null  int32
 11  Arrival_Day           10682 non-null  int32
 12  Journey_Diff_Days     10682 non-null  int64
 13  Duration_hours        10682 non-null  float64
 14  Duration_minutes      10682 non-null  int32
 15  Duration_total_mins   10682 non-null  float64
 16  Additional_Info_flag  10682 non-null  int64
dtypes: float64(2), int32(9), int64(3), object(3)
memory usage: 1.1+ MB

In [267]:
# Train Test Split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [268]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8545 entries, 10005 to 7270
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Airline               8545 non-null   object
 1   Source                8545 non-null   object
 2   Destination           8545 non-null   object
 3   Total_Stops           8545 non-null   int64
 4   Journey_day           8545 non-null   int32
 5   Journey_month         8545 non-null   int32
 6   Journey_weekday       8545 non-null   int32
 7   Dep_hour              8545 non-null   int32
 8   Dep_min               8545 non-null   int32
 9   Arrival_hour          8545 non-null   int32
 10  Arrival_min           8545 non-null   int32
 11  Arrival_Day           8545 non-null   int32
 12  Journey_Diff_Days     8545 non-null   int64
 13  Duration_hours        8545 non-null   float64
 14  Duration_minutes      8545 non-null   int32
 15  Duration_total_mins   8545 non-null   float64
 16  Additional_Info_flag  8545 non-null   int64
dtypes: float64(2), int32(9), int64(3), object(3)
memory usage: 901.2+ KB

In [271]:
# 2. PREPROCESSING PIPELINE
# =====================================================
# Identify numeric and categorical columns
numeric_features = X_train.select_dtypes(include=["int64", "float64","int32"]).columns.tolist()
categorical_features = X_train.select_dtypes(include=["object"]).columns.tolist()

# Create preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(drop="first", sparse_output=False, handle_unknown='ignore'), categorical_features),
         ]
)

In [272]:
# =====================================================
# 3. RANDOM FOREST PIPELINE
# =====================================================
rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(n_estimators=160, max_depth=20, random_state=42))
])

rf_pipeline.fit(X_train, Y_train)
rf_pipe_pred = rf_pipeline.predict(X_test)

print("=== RANDOM FOREST WITH PIPELINE ===")
print(f"MAE: {mean_absolute_error(Y_test, rf_pipe_pred):.2f}")
print(f"RMSE: {np.sqrt(mean_squared_error(Y_test, rf_pipe_pred)):.2f}")
print(f"R²: {r2_score(Y_test, rf_pipe_pred):.4f}\n")

=== RANDOM FOREST WITH PIPELINE ===
MAE: 623.88
RMSE: 1443.59
R²: 0.9034

In [273]:
# =====================================================
# 4. XGBOOST PIPELINE
# =====================================================
xgb_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", XGBRegressor(
        n_estimators=200,
        max_depth=8,
        learning_rate=0.1,
        subsample=0.8,
        random_state=42,
        tree_method="hist"
    ))
])

xgb_pipeline.fit(X_train, Y_train)
xgb_pred = xgb_pipeline.predict(X_test)

print("=== XGBOOST WITH PIPELINE ===")
print(f"MAE: {mean_absolute_error(Y_test, xgb_pred):.2f}")
print(f"RMSE: {np.sqrt(mean_squared_error(Y_test, xgb_pred)):.2f}")
print(f"R²: {r2_score(Y_test, xgb_pred):.4f}\n")

=== XGBOOST WITH PIPELINE ===
MAE: 665.69
RMSE: 1329.24
R²: 0.9181

In [274]:
# =====================================================
# 5. LIGHTGBM PIPELINE
# =====================================================
lgb_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LGBMRegressor(
        n_estimators=200,
        max_depth=12,
        learning_rate=0.1,
        random_state=42,
        n_jobs=-1,
        verbose=-1
    ))
])

lgb_pipeline.fit(X_train, Y_train)
lgb_pred = lgb_pipeline.predict(X_test)

print("=== LIGHTGBM WITH PIPELINE ===")
print(f"MAE: {mean_absolute_error(Y_test, lgb_pred):.2f}")
print(f"RMSE: {np.sqrt(mean_squared_error(Y_test, lgb_pred)):.2f}")
print(f"R²: {r2_score(Y_test, lgb_pred):.4f}\n")

=== LIGHTGBM WITH PIPELINE ===
MAE: 809.80
RMSE: 1470.03
R²: 0.8998

##### Cross Validation

In [275]:
# =====================================================
# 6. CROSS-VALIDATION WITH PIPELINE
# =====================================================
print("=== CROSS-VALIDATION SCORES ===")
rf_cv = cross_val_score(rf_pipeline, X_train, Y_train, cv=5, scoring="r2")
print(f"Random Forest CV R² (mean ± std): {rf_cv.mean():.4f} ± {rf_cv.std():.4f}")

xgb_cv = cross_val_score(xgb_pipeline, X_train, Y_train, cv=5, scoring="r2")
print(f"XGBoost CV R² (mean ± std): {xgb_cv.mean():.4f} ± {xgb_cv.std():.4f}")

lgb_cv = cross_val_score(lgb_pipeline, X_train, Y_train, cv=5, scoring="r2")
print(f"LightGBM CV R² (mean ± std): {lgb_cv.mean():.4f} ± {lgb_cv.std():.4f}\n")

=== CROSS-VALIDATION SCORES ===
Random Forest CV R² (mean ± std): 0.8850 ± 0.0134
XGBoost CV R² (mean ± std): 0.8971 ± 0.0198
LightGBM CV R² (mean ± std): 0.8592 ± 0.0350

##### Hyperparameter Tunning

In [276]:
# =====================================================
# 7. HYPERPARAMETER TUNING WITH PIPELINE
# =====================================================
param_grid = {
    "model__n_estimators": [50, 100, 200],
    "model__max_depth": [5, 7, 10],
    "model__learning_rate": [0.05, 0.1]
}

grid_search = GridSearchCV(
    xgb_pipeline,
    param_grid,
    cv=3,
    scoring="r2",
    n_jobs=-1
)

grid_search.fit(X_train, Y_train)

print("=== GRID SEARCH RESULTS ===")
print(f"Best Parameters: {grid_search.best_params_}")
print(f"Best CV Score: {grid_search.best_score_:.4f}")

best_pred = grid_search.predict(X_test)
print(f"Test R²: {r2_score(Y_test, best_pred):.4f}\n")

=== GRID SEARCH RESULTS ===
Best Parameters: {'model__learning_rate': 0.05, 'model__max_depth': 10, 'model__n_estimators': 200}
Best CV Score: 0.8853
Test R²: 0.9135

**As we can see clearly that after hyperparamter tunning the R square values get improve a little bit.**

##### Save/Drop the Model

In [277]:

# =====================================================
# 8. SAVE PIPELINE
# =====================================================
import joblib
joblib.dump(xgb_pipeline, "xgb_pipeline_model.pkl")
print("✓ Pipeline saved as 'xgb_pipeline_model.pkl'")

✓ Pipeline saved as 'xgb_pipeline_model.pkl'

##### Checking new data on model

In [289]:
new_data = pd.DataFrame({
    'Airline': ['IndiGo'],
    'Source': ['Delhi'],
    'Destination': ['Cochin'],
    'Total_Stops': [1],
    'Journey_day': [10],
    'Journey_month': [6],
    'Journey_weekday': [2],
    'Dep_hour': [14],
    'Dep_min': [30],
    'Arrival_hour': [18],
    'Arrival_min': [45],
    'Arrival_Day': [10],
    'Journey_Diff_Days': [0],
    'Duration_hours': [4],
    'Duration_minutes': [15],
    'Duration_total_mins': [255],
    'Additional_Info_flag': [0]
})

In [290]:
new_data = new_data[X_train.columns]  # It confirm that new_data has same columns as X_train and in same order, filling missing columns with 0 if any

In [291]:
prediction = xgb_pipeline.predict(new_data)

print("Predicted Price:", prediction[0])

Predicted Price: 5566.0864

In [278]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8545 entries, 10005 to 7270
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Airline               8545 non-null   object
 1   Source                8545 non-null   object
 2   Destination           8545 non-null   object
 3   Total_Stops           8545 non-null   int64
 4   Journey_day           8545 non-null   int32
 5   Journey_month         8545 non-null   int32
 6   Journey_weekday       8545 non-null   int32
 7   Dep_hour              8545 non-null   int32
 8   Dep_min               8545 non-null   int32
 9   Arrival_hour          8545 non-null   int32
 10  Arrival_min           8545 non-null   int32
 11  Arrival_Day           8545 non-null   int32
 12  Journey_Diff_Days     8545 non-null   int64
 13  Duration_hours        8545 non-null   float64
 14  Duration_minutes      8545 non-null   int32
 15  Duration_total_mins   8545 non-null   float64
 16  Additional_Info_flag  8545 non-null   int64
dtypes: float64(2), int32(9), int64(3), object(3)
memory usage: 901.2+ KB